name: Deploy to Production
on: 
  workflow_dispatch:
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - name: Say Hello World
        run: echo 'Hello, world!'
